name: CI tests

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2022
    steps:
    
    - name: Debug workflow context
      run: |
        echo "Event name: ${{ github.event_name }}"
        echo "Ref: ${{ github.ref }}"
        echo "Head ref: ${{ github.head_ref }}"
        echo "Base ref: ${{ github.base_ref }}"
        echo "SHA: ${{ github.sha }}"
        echo "Repository: ${{ github.repository }}"
        
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.sln*', '**/*.csproj*') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
     
    - name: Restore NuGet packages
      run: |
        nuget restore updater.csproj -ConfigFile nuget.config

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    
    - name: Build solution for testing
      run: |
        dotnet build updater.csproj --configuration Debug
        dotnet build ConfigManager/ProgramUpdater.ConfigManager.csproj --configuration Debug
